title: hello-world
description: This is just for learning. You can delete it.
template:
  repo: hello-world-template
  name: hello-world
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
  - title: New step
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
